/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 20-Jan-2021 10:22:28 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE [shared].[LocationInfo]
(
	[LocationType] varchar(2000) NULL,
	[LocationInfoID] int NOT NULL IDENTITY (1, 1),
	[PersonID] int NULL,
	[ClinicalSiteID] int NULL,
	[OrganizationID] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [shared].[LocationInfo] 
 ADD CONSTRAINT [PK_LocationInfo]
	PRIMARY KEY CLUSTERED ([LocationInfoID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [shared].[LocationInfo] ADD CONSTRAINT [FK_LocationInfo_ClinicalSite]
	FOREIGN KEY ([ClinicalSiteID]) REFERENCES [clinical].[ClinicalSite] ([ClinicalSiteID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [shared].[LocationInfo] ADD CONSTRAINT [FK_LocationInfo_Organization]
	FOREIGN KEY ([OrganizationID]) REFERENCES [shared].[Organization] ([OrganizationID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [shared].[LocationInfo] ADD CONSTRAINT [FK_LocationInfo_Person]
	FOREIGN KEY ([PersonID]) REFERENCES [shared].[Person] ([PersonID]) ON DELETE No Action ON UPDATE No Action
GO
