CREATE TABLE [dbo].[ActiveEmployees] (
    [RowID]                INT             NOT NULL,
    [EmployeeID]           VARCHAR (15)    NOT NULL,
    [LastName]             VARCHAR (30)    NOT NULL,
    [FirstName]            VARCHAR (30)    NULL,
    [NickName]             NVARCHAR (30)   NULL,
    [MiddleName]           NVARCHAR (30)   NULL,
    [WorkPhone]            VARCHAR (41)    NULL,
    [CellPhone]            VARCHAR (41)    NULL,
    [Email]                VARCHAR (30)    NULL,
    [Title]                VARCHAR (80)    NULL,
    [ReportsToEmployeeID]  VARCHAR (15)    NULL,
    [CompanyCode]          VARCHAR (15)    NULL,
    [Department]           VARCHAR (80)    NULL,
    [Building]             VARCHAR (15)    NULL,
    [DepartmentCode]       VARCHAR (15)    NULL,
    [EndDate]              DATETIME        NULL,
    [ExemptStatus]         VARCHAR (15)    NOT NULL,
    [FullTimeEquivalent]   NUMERIC (19, 4) NOT NULL,
    [PersonJobStartDate]   DATETIME        NOT NULL,
    [StatusCode]           VARCHAR (15)    NOT NULL,
    [WorkStatus]           VARCHAR (15)    NULL,
    [Picture]              IMAGE           NULL,
    [StockLevelCode]       VARCHAR (15)    NULL,
    [JobCode]              VARCHAR (20)    NULL,
    [JobDescription]       VARCHAR (55)    NULL,
    [Inserted]             DATETIME        CONSTRAINT [INSERTED_DATE] DEFAULT (getdate()) NOT NULL,
    [StatusStartDate]      DATETIME        NULL,
    [EEOEstablishmentName] VARCHAR (72)    NULL,
    [test] NCHAR(10) NULL, 
    PRIMARY KEY CLUSTERED ([RowID] ASC)
);