CREATE TABLE [dbo].[AdaptiveRootAccounts] (
    [id]                   INT           NULL,
    [code]                 VARCHAR (50)  NULL,
    [name]                 VARCHAR (100) NULL,
    [description]          VARCHAR (100) NULL,
    [timeStratum]          VARCHAR (50)  NULL,
    [displayAs]            VARCHAR (50)  NULL,
    [accountTypeCode]      VARCHAR (50)  NULL,
    [decimalPrecision]     INT           NULL,
    [isAssumption]         VARCHAR (50)  NULL,
    [suppressZeroes]       VARCHAR (50)  NULL,
    [isDefaultRoot]        VARCHAR (50)  NULL,
    [shortName]            VARCHAR (50)  NULL,
    [exchangeRateType]     VARCHAR (50)  NULL,
    [balanceType]          VARCHAR (50)  NULL,
    [isLinked]             VARCHAR (50)  NULL,
    [owningSheetId]        VARCHAR (50)  NULL,
    [isSystem]             VARCHAR (50)  NULL,
    [isIntercompany]       VARCHAR (50)  NULL,
    [dataEntryType]        VARCHAR (50)  NULL,
    [planBy]               VARCHAR (50)  NULL,
    [actualsBy]            VARCHAR (50)  NULL,
    [timeRollup]           VARCHAR (50)  NULL,
    [timeWeightAcctId]     VARCHAR (50)  NULL,
    [levelDimRollup]       VARCHAR (50)  NULL,
    [levelDimWeightAcctId] VARCHAR (50)  NULL,
    [rollupText]           VARCHAR (50)  NULL,
    [startExpanded]        VARCHAR (50)  NULL,
    [hasSalaryDetail]      VARCHAR (50)  NULL,
    [dataPrivacy]          VARCHAR (50)  NULL,
    [isBreakbackEligible]  VARCHAR (50)  NULL,
    [subType]              VARCHAR (50)  NULL,
    [enableActuals]        VARCHAR (50)  NULL,
    [isGroup]              VARCHAR (50)  NULL,
    [hasFormula]           VARCHAR (50)  NULL,
    [parentId]             INT           NULL,
    [parentCode]           VARCHAR (50)  NULL
);

