CREATE TABLE [dbo].[AssetFixedAssetStaging] (
    [CONTACTNAME]                                       NVARCHAR (100)  NOT NULL,
    [RESPONSIBLENAME]                                   NVARCHAR (100)  NOT NULL,
    [DEFINITIONGROUP]                                   NVARCHAR (60)   NOT NULL,
    [EXECUTIONID]                                       NVARCHAR (90)   NOT NULL,
    [ISSELECTED]                                        INT             NOT NULL,
    [TRANSFERSTATUS]                                    INT             NOT NULL,
    [AGENT]                                             NVARCHAR (60)   NOT NULL,
    [ACTIVITYCODE]                                      NVARCHAR (10)   NOT NULL,
    [ACTIVITYCODEDESCRIPTION]                           NVARCHAR (60)   NOT NULL,
    [ASSETCONDITIONID]                                  NVARCHAR (20)   NOT NULL,
    [ASSETCONDITIONDESCRIPTION]                         NVARCHAR (60)   NOT NULL,
    [BARCODE]                                           NVARCHAR (20)   NOT NULL,
    [COMMENTS]                                          NVARCHAR (MAX)  NULL,
    [CONTACTPERSONNELNUMBER]                            NVARCHAR (25)   NOT NULL,
    [DEPARTMENTOPERATINGUNITNUMBER]                     NVARCHAR (30)   NOT NULL,
    [DEPARTMENTSEARCHNAME]                              NVARCHAR (60)   NOT NULL,
    [DISPOSALRESTRICTIONS]                              NVARCHAR (1000) NOT NULL,
    [DOCUMENTLOCATION]                                  NVARCHAR (259)  NOT NULL,
    [FIXEDASSETGROUPID]                                 NVARCHAR (10)   NOT NULL,
    [FIXEDASSETNUMBER]                                  NVARCHAR (20)   NOT NULL,
    [GISREFERENCENUMBER]                                NVARCHAR (50)   NOT NULL,
    [GUARANTEEDATE]                                     DATETIME        NOT NULL,
    [INFORMATION1]                                      NVARCHAR (254)  NOT NULL,
    [INFORMATION2]                                      NVARCHAR (254)  NOT NULL,
    [INFORMATION3]                                      NVARCHAR (MAX)  NULL,
    [INSURANCEDATE1]                                    DATETIME        NOT NULL,
    [INSURANCEDATE2]                                    DATETIME        NOT NULL,
    [INSURANCEVENDOR]                                   NVARCHAR (20)   NOT NULL,
    [INSUREDATFAIRMARKETVALUE]                          INT             NOT NULL,
    [INSUREDVALUE]                                      NUMERIC (32, 6) NOT NULL,
    [LASTPERIODICVALUECOSTUPDATE]                       DATETIME        NOT NULL,
    [LASTMAINTENANCE]                                   DATETIME        NOT NULL,
    [LEASENOTE]                                         NVARCHAR (1000) NOT NULL,
    [ASSETLOCATIONID]                                   NVARCHAR (10)   NOT NULL,
    [ASSETLOCATIONNAME]                                 NVARCHAR (30)   NOT NULL,
    [LOCATIONID]                                        NVARCHAR (30)   NOT NULL,
    [LOCATIONMEMO]                                      NVARCHAR (1000) NOT NULL,
    [MAJORTYPEID]                                       NVARCHAR (20)   NOT NULL,
    [MAJORTYPEDESCRIPTION]                              NVARCHAR (60)   NOT NULL,
    [MAKE]                                              NVARCHAR (60)   NOT NULL,
    [MISSINGASSET]                                      INT             NOT NULL,
    [MODEL]                                             NVARCHAR (60)   NOT NULL,
    [MODELYEAR]                                         NVARCHAR (10)   NOT NULL,
    [NAME]                                              NVARCHAR (30)   NOT NULL,
    [NEXTMAINTENANCE]                                   DATETIME        NOT NULL,
    [PARCELID]                                          NVARCHAR (50)   NOT NULL,
    [PHYSICALINVENTORY]                                 DATETIME        NOT NULL,
    [POLICYAMOUNT]                                      NUMERIC (32, 6) NOT NULL,
    [POLICYEXPIRATIONDATE]                              DATETIME        NOT NULL,
    [POLICYNUMBER]                                      NVARCHAR (20)   NOT NULL,
    [PROPERTYGROUPID]                                   NVARCHAR (10)   NOT NULL,
    [PROPERTYGROUPDESCRIPTION]                          NVARCHAR (60)   NOT NULL,
    [PROPERTYTYPE]                                      INT             NOT NULL,
    [QUANTITY]                                          NUMERIC (32, 6) NOT NULL,
    [REFERENCE]                                         NVARCHAR (254)  NOT NULL,
    [REPLACEMENTCOST]                                   NUMERIC (32, 6) NOT NULL,
    [RESPONSIBLEPERSONNELNUMBER]                        NVARCHAR (25)   NOT NULL,
    [ROOMNUMBER]                                        NVARCHAR (20)   NOT NULL,
    [SEARCHNAME]                                        NVARCHAR (60)   NOT NULL,
    [SERIALNUMBER]                                      NVARCHAR (25)   NOT NULL,
    [SORTFIELD1ID]                                      NVARCHAR (10)   NOT NULL,
    [SORTFIELD1SORTING]                                 INT             NOT NULL,
    [SORTFIELD1DESCRIPTION]                             NVARCHAR (60)   NOT NULL,
    [SORTFIELD2ID]                                      NVARCHAR (10)   NOT NULL,
    [SORTFIELD2SORTING]                                 INT             NOT NULL,
    [SORTFIELD2DESCRIPTION]                             NVARCHAR (60)   NOT NULL,
    [SORTFIELD3ID]                                      NVARCHAR (10)   NOT NULL,
    [SORTFIELD3SORTING]                                 INT             NOT NULL,
    [SORTFIELD3DESCRIPTION]                             NVARCHAR (60)   NOT NULL,
    [TECHNICALINFORMATION1]                             NVARCHAR (254)  NOT NULL,
    [TECHNICALINFORMATION2]                             NVARCHAR (254)  NOT NULL,
    [TECHNICALINFORMATION3]                             NVARCHAR (254)  NOT NULL,
    [TITLEHOLDER]                                       NVARCHAR (60)   NOT NULL,
    [TYPE]                                              INT             NOT NULL,
    [UNITCOST]                                          NUMERIC (32, 6) NOT NULL,
    [UNITOFMEASURE]                                     NVARCHAR (10)   NOT NULL,
    [ACCELERATEDDEPRECIATIONFIXEDASSETEQUIPMENTGROUPID] NVARCHAR (10)   NOT NULL,
    [ASSETCLASSIFICATION]                               INT             NOT NULL,
    [EXCEPTIONTAXATIONCODE]                             NVARCHAR (10)   NOT NULL,
    [DEFERREDTYPE]                                      INT             NOT NULL,
    [EXCEPTIONTAXATIONRATEDENOMINATOR]                  NUMERIC (32, 6) NOT NULL,
    [EXCEPTIONTAXATIONRATE]                             NUMERIC (32, 6) NOT NULL,
    [ISSECONDHAND]                                      INT             NOT NULL,
    [ASSETTYPEOFMAJORTYPE]                              INT             NOT NULL,
    [NAMEOFTHELENDER]                                   NVARCHAR (60)   NOT NULL,
    [ISRENTED]                                          INT             NOT NULL,
    [RESOURCE_]                                         NVARCHAR (10)   NOT NULL,
    [PHYSICALASSETNUMBER]                               NVARCHAR (30)   NOT NULL,
    [LONGTERMRECEIVABLETAX]                             INT             NOT NULL,
    [OUTGOINGICMS]                                      INT             NOT NULL,
    [ICMSCREDITINSTALLMENTS]                            INT             NOT NULL,
    [TRANSFERREDFROMINVENTORY]                          INT             NOT NULL,
    [TAXATIONCODEFORCOFINS]                             NVARCHAR (3)    NOT NULL,
    [APPROPRIATIONMETHOD]                               INT             NOT NULL,
    [FIXEDASSETCREDITGROUP]                             INT             NOT NULL,
    [TAXCREDITSINSTALLMENTS]                            INT             NOT NULL,
    [TAXCREDITPURPOSE]                                  INT             NOT NULL,
    [TAXATIONCODEFORPIS]                                NVARCHAR (3)    NOT NULL,
    [FISCALESTABLISHMENTID]                             NVARCHAR (10)   NOT NULL,
    [SOURCETYPEID]                                      NVARCHAR (10)   NOT NULL,
    [MAINASSETID]                                       NVARCHAR (20)   NOT NULL,
    [PARTITION]                                         NVARCHAR (20)   NOT NULL,
    [DATAAREAID]                                        NVARCHAR (4)    NOT NULL,
    [SYNCSTARTDATETIME]                                 DATETIME        NOT NULL,
    CONSTRAINT [PK_AssetFixedAssetStaging] PRIMARY KEY CLUSTERED ([EXECUTIONID] ASC, [FIXEDASSETGROUPID] ASC, [FIXEDASSETNUMBER] ASC, [DATAAREAID] ASC, [PARTITION] ASC)
);

