CREATE TABLE [dbo].[AssetJournalEntityStaging] (
    [DEFINITIONGROUP]              NVARCHAR (60)    NOT NULL,
    [EXECUTIONID]                  NVARCHAR (90)    NOT NULL,
    [ISSELECTED]                   INT              NOT NULL,
    [TRANSFERSTATUS]               INT              NOT NULL,
    [CREDITAMOUNT]                 NUMERIC (32, 6)  NOT NULL,
    [DEBITAMOUNT]                  NUMERIC (32, 6)  NOT NULL,
    [JOURNALBATCHNUMBER]           NVARCHAR (60)    NOT NULL,
    [ACCOUNTDISPLAYVALUE]          NVARCHAR (500)   NOT NULL,
    [OFFSETACCOUNTTYPE]            INT              NOT NULL,
    [OFFSETACCOUNTDISPLAYVALUE]    NVARCHAR (500)   NOT NULL,
    [TRANSDATE]                    DATETIME         NOT NULL,
    [TEXT]                         NVARCHAR (512)   NOT NULL,
    [VOUCHER]                      NVARCHAR (60)    NOT NULL,
    [CURRENCYCODE]                 NVARCHAR (3)     NOT NULL,
    [POSTINGLAYER]                 INT              NOT NULL,
    [JOURNALNAMEID]                NVARCHAR (10)    NOT NULL,
    [LINENUMBER]                   NUMERIC (32, 16) NOT NULL,
    [ISPOSTED]                     INT              NOT NULL,
    [DESCRIPTION]                  NVARCHAR (60)    NOT NULL,
    [VALUEMODELID]                 NVARCHAR (10)    NOT NULL,
    [TRANSACTIONTYPE]              INT              NOT NULL,
    [ACCOUNTTYPE]                  INT              NOT NULL,
    [CONSUMPTIONUNITS]             NUMERIC (32, 6)  NOT NULL,
    [EXCHANGERATE]                 NUMERIC (32, 16) NOT NULL,
    [CHINESEVOUCHERTYPE]           NVARCHAR (10)    NOT NULL,
    [CHINESEVOUCHER]               NVARCHAR (60)    NOT NULL,
    [DEFAULTDIMENSIONDISPLAYVALUE] NVARCHAR (500)   NOT NULL,
    [PARTITION]                    NVARCHAR (20)    NOT NULL,
    [DATAAREAID]                   NVARCHAR (4)     NOT NULL,
    [SYNCSTARTDATETIME]            DATETIME         NOT NULL,
    CONSTRAINT [PK_AssetJournalEntityStaging] PRIMARY KEY CLUSTERED ([EXECUTIONID] ASC, [JOURNALBATCHNUMBER] ASC, [LINENUMBER] ASC, [DATAAREAID] ASC, [PARTITION] ASC)
);

