CREATE TABLE [dbo].[BudgetRegisterEntryStaging] (
    [BUDGETMODELID]             NVARCHAR (10)    NOT NULL,
    [STATUS]                    INT              NOT NULL,
    [DIMENSIONACCOUNTSTRUCTURE] NVARCHAR (60)    NOT NULL,
    [DIMENSIONDISPLAYVALUE]     NVARCHAR (500)   NOT NULL,
    [ENTRYNUMBER]               NVARCHAR (20)    NOT NULL,
    [REASONCODE]                NVARCHAR (10)    NOT NULL,
    [REASONCOMMENT]             NVARCHAR (60)    NOT NULL,
    [DEFINITIONGROUP]           NVARCHAR (60)    NOT NULL,
    [EXECUTIONID]               NVARCHAR (90)    NOT NULL,
    [ISSELECTED]                INT              NOT NULL,
    [TRANSFERSTATUS]            INT              NOT NULL,
    [ACCOUNTINGCURRENCYAMOUNT]  NUMERIC (32, 6)  NOT NULL,
    [AMOUNTTYPE]                INT              NOT NULL,
    [BUDGETCODE]                NVARCHAR (20)    NOT NULL,
    [BUDGETTYPE]                INT              NOT NULL,
    [COMMENT_]                  NVARCHAR (60)    NOT NULL,
    [CURRENCYCODE]              NVARCHAR (3)     NOT NULL,
    [DATE]                      DATETIME         NOT NULL,
    [INCLUDEINCASHFLOWFORECAST] INT              NOT NULL,
    [LEGALENTITYID]             NVARCHAR (4)     NOT NULL,
    [LINENUMBER]                NUMERIC (32, 16) NOT NULL,
    [ONETIMEREVISION]           INT              NOT NULL,
    [PRICE]                     NUMERIC (32, 6)  NOT NULL,
    [QUANTITY]                  NUMERIC (32, 6)  NOT NULL,
    [TRANSACTIONCURRENCYAMOUNT] NUMERIC (32, 6)  NOT NULL,
    [LINEWORKFLOWSTATUS]        INT              NOT NULL,
    [DOCUMENTWORKFLOWSTATUS]    INT              NOT NULL,
    [PARTITION]                 NVARCHAR (20)    NOT NULL,
    [DATAAREAID]                NVARCHAR (4)     NOT NULL,
    [SYNCSTARTDATETIME]         DATETIME         NOT NULL,
    [RECID]                     BIGINT           NOT NULL,
    CONSTRAINT [PK_BudgetRegisterEntryStaging] PRIMARY KEY CLUSTERED ([ENTRYNUMBER] ASC, [EXECUTIONID] ASC, [TRANSFERSTATUS] ASC, [LEGALENTITYID] ASC, [LINENUMBER] ASC, [DATAAREAID] ASC, [PARTITION] ASC)
);

