CREATE TABLE [dbo].[CoupaPOLine] (
    [ID]                        INT             NULL,
    [Order_Header_ID]           INT             NULL,
    [Order_Header_Number]       VARCHAR (20)    NULL,
    [Department]                VARCHAR (100)   NULL,
    [Account]                   VARCHAR (500)   NULL,
    [Line_Num]                  VARCHAR (255)   NULL,
    [Description]               VARCHAR (500)   NULL,
    [Contract]                  VARCHAR (100)   NULL,
    [Supplier_Order_Number]     VARCHAR (50)    NULL,
    [Supplier_Site_ID]          VARCHAR (50)    NULL,
    [Item]                      VARCHAR (500)   NULL,
    [UOM]                       VARCHAR (20)    NULL,
    [Source_Part_Num]           VARCHAR (500)   NULL,
    [Commodity]                 VARCHAR (200)   NULL,
    [Accounting_Total]          DECIMAL (32, 4) NULL,
    [Accounting_Total_Currency] VARCHAR (20)    NULL,
    [Reporting_Total]           DECIMAL (32, 4) NULL,
    [Total]                     DECIMAL (32, 4) NULL,
    [Currency]                  VARCHAR (20)    NULL,
    [Bulk_Price]                DECIMAL (32, 4) NULL,
    [Price]                     DECIMAL (30, 6) NULL,
    [Quantity]                  DECIMAL (30, 6) NULL,
    [Invoiced]                  DECIMAL (30, 6) NULL,
    [Period]                    VARCHAR (20)    NULL,
    [Received]                  DECIMAL (30, 6) NULL,
    [Receiving_Warehouse]       VARCHAR (100)   NULL,
    [Type]                      VARCHAR (100)   NULL,
    [Version]                   INT             NULL
);

