CREATE TABLE [dbo].[DimensionAttributeStaging](
	[DEFINITIONGROUP] [nvarchar](60) NOT NULL,
	[EXECUTIONID] [nvarchar](90) NOT NULL,
	[ISSELECTED] [int] NOT NULL,
	[TRANSFERSTATUS] [int] NOT NULL,
	[DIMENSIONNAME] [nvarchar](60) NOT NULL,
	[REPORTCOLUMNNAME] [nvarchar](6) NOT NULL,
	[USEVALUESFROM] [nvarchar](60) NOT NULL,
	[DIMENSIONVALUEMASK] [nvarchar](30) NOT NULL,
	[PARTITION] [nvarchar](20) NOT NULL,
	[COPYVALUESONCREATE] [int] NOT NULL,
	[GIVEDERIVEDDIMENSIONSPRECEDENCE] [int] NOT NULL,
	[ISBALANCING_PSN] [int] NOT NULL,
	[BALANCINGDIMENSION_PSN] [bigint] NOT NULL
) ON [PRIMARY]
GO
