/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 22-Oct-2020 10:03:19 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE [dbo].[DimFinancialCalendar]
(
	[FiscalPeriodKey] int NOT NULL IDENTITY (1, 1),
	[EntityKey] int NULL,
	[FiscalMonth] int NOT NULL,
	[MonthNumer] int NULL,
	[MonthName] nvarchar(30) NULL,
	[DayNumber] int NULL,
	[Year] int NULL,
	[FullDate] date NULL,
	[Quarter] varchar(2) NULL,
	[FiscalYear] nvarchar(10) NOT NULL,
	[PeriodName] nvarchar(60) NOT NULL,
	[ShortName] nvarchar(8) NOT NULL,
	[StartDate] datetime NOT NULL,
	[EndDate] datetime NOT NULL,
	[Type] int NOT NULL,
	[Calendar] nvarchar(10) NOT NULL,
	[CalendarType] int NOT NULL,
	[Days] int NOT NULL,
	[CYTDFlag] int NULL,
	[PYTDFlag] int NULL,
	[CYQuarterToDate] int NULL,
	[PYQuarterToDate] int NULL,
	[CYMonthToDate] int NULL,
	[PYMonthToDate] int NULL,
	[Rolling12Closed] int NULL,
	[OpenClosed] varchar(50) NULL,
	[LastClosedMonth] int NULL,
	[PQuarterToDate] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[DimFinancialCalendar] 
 ADD CONSTRAINT [PK_DimFinancialCalendar]
	PRIMARY KEY CLUSTERED ([FiscalPeriodKey] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_DimFinancialCalendar] 
 ON [dbo].[DimFinancialCalendar] ([FullDate] ASC,[EntityKey] ASC)
GO