/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 22-Oct-2020 10:03:19 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE [DimScenarioType]
(
	[ScenarioTypeKey] int NOT NULL IDENTITY (1, 1),
	[ScenarioType] varchar(50) NOT NULL,
	[RichWasHere] varchar(50) NULL,
	[ScenarioKey] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [DimScenarioType] 
 ADD CONSTRAINT [PK_DimScenarioType]
	PRIMARY KEY CLUSTERED ([ScenarioTypeKey] ASC)
GO