CREATE TABLE [dbo].[MainAccountStaging] (
    [OFFSETACCOUNTDISPLAYVALUE]                 NVARCHAR (500) NOT NULL,
    [PARENTMAINACCOUNTID]                       NVARCHAR (20)  NOT NULL,
    [DEFINITIONGROUP]                           NVARCHAR (60)  NOT NULL,
    [EXECUTIONID]                               NVARCHAR (90)  NOT NULL,
    [ISSELECTED]                                INT            NOT NULL,
    [TRANSFERSTATUS]                            INT            NOT NULL,
    [MAINACCOUNTCATEGORY]                       NVARCHAR (20)  NOT NULL,
    [CLOSING]                                   INT            NOT NULL,
    [DEFAULTCONSOLIDATIONACCOUNT]               NVARCHAR (10)  NOT NULL,
    [DEFAULTCURRENCY]                           NVARCHAR (3)   NOT NULL,
    [BALANCECONTROL]                            INT            NOT NULL,
    [DEBITCREDITREQUIREMENT]                    INT            NOT NULL,
    [DEBITCREDITDEFAULT]                        INT            NOT NULL,
    [FOREIGNCURRENCYREVALUATION]                INT            NOT NULL,
    [FINANCIALREPORTINGCURRENCYTRANSLATIONTYPE] INT            NOT NULL,
    [CHARTOFACCOUNTSRECID]                      BIGINT         NOT NULL,
    [MAINACCOUNTID]                             NVARCHAR (20)  NOT NULL,
    [MANDATORYPAYMENTREFERENCE]                 INT            NOT NULL,
    [MONETARY]                                  INT            NOT NULL,
    [NAME]                                      NVARCHAR (60)  NOT NULL,
    [POSTINGTYPE]                               INT            NOT NULL,
    [SRUCODE]                                   NVARCHAR (4)   NOT NULL,
    [MAINACCOUNTTYPE]                           INT            NOT NULL,
    [USER_]                                     NVARCHAR (20)  NOT NULL,
    [VALIDATECURRENCY]                          INT            NOT NULL,
    [VALIDATEPOSTINGTYPE]                       INT            NOT NULL,
    [VALIDATEUSER]                              INT            NOT NULL,
    [OPENINGACCOUNTID]                          NVARCHAR (20)  NOT NULL,
    [CHARTOFACCOUNTS]                           NVARCHAR (60)  NOT NULL,
    [REPORTINGACCOUNTTYPE]                      INT            NOT NULL,
    [FINANCIALREPORTINGEXCHANGERATETYPE]        NVARCHAR (20)  NOT NULL,
    [DONOTALLOWMANUALENTRY]                     INT            NOT NULL,
    [ISSUSPENDED]                               INT            NOT NULL,
    [ACTIVEFROM]                                DATETIME       NOT NULL,
    [ACTIVETO]                                  DATETIME       NOT NULL,
    [MAINACCOUNTRECID]                          BIGINT         NOT NULL,
    [ACCOUNTCATEGORYDESCRIPTION]                NVARCHAR (60)  NOT NULL,
    [ADJUSTMENTMETHOD]                          INT            NOT NULL,
    [INFLATIONADJUSTMENT]                       INT            NOT NULL,
    [REPOMOTYPE]                                INT            NOT NULL,
    [EXCHANGEADJUSTMENTRATETYPE]                NVARCHAR (20)  NOT NULL,
    [REPORTINGEXCHANGEADJUSTMENTRATETYPE]       NVARCHAR (20)  NOT NULL,
    [PARTITION]                                 NVARCHAR (20)  NOT NULL,
    [SYNCSTARTDATETIME]                         DATETIME       NOT NULL,
    [RECID]                                     BIGINT         NOT NULL,
    CONSTRAINT [PK_MainAccountStaging] PRIMARY KEY CLUSTERED ([EXECUTIONID] ASC, [MAINACCOUNTID] ASC, [CHARTOFACCOUNTS] ASC, [PARTITION] ASC)
);

