CREATE TABLE [dbo].[SystemUserStaging] (
    [PERSONNAME]                                       NVARCHAR (60)    NOT NULL,
    [DEFINITIONGROUP]                                  NVARCHAR (60)    NOT NULL,
    [EXECUTIONID]                                      NVARCHAR (90)    NOT NULL,
    [ISSELECTED]                                       INT              NOT NULL,
    [TRANSFERSTATUS]                                   INT              NOT NULL,
    [DEFAULTCOUNTRYREGION]                             NVARCHAR (10)    NOT NULL,
    [DOCUMENTHANDLINGACTIVE]                           INT              NOT NULL,
    [SHOWATTACHMENTSTATUS]                             INT              NOT NULL,
    [EMAIL]                                            NVARCHAR (80)    NOT NULL,
    [SENDALERTASEMAILMESSAGE]                          INT              NOT NULL,
    [EVENTPOLLFREQUENCY]                               INT              NOT NULL,
    [EVENTPOPUPDISPLAYWHEN]                            INT              NOT NULL,
    [EVENTPOPUPLINKDESTINATION]                        INT              NOT NULL,
    [EVENTPOPUPS]                                      INT              NOT NULL,
    [EVENTWORKFLOWSHOWPOPUP]                           INT              NOT NULL,
    [SHOWNOTIFICATIONSINTHEMICROSOFTDYNAMICSAX7CLIENT] INT              NOT NULL,
    [SENDNOTIFICATIONSINEMAIL]                         INT              NOT NULL,
    [MARKEMPTYLINKS]                                   INT              NOT NULL,
    [USERID]                                           NVARCHAR (20)    NOT NULL,
    [LANGUAGE]                                         NVARCHAR (7)     NOT NULL,
    [SQMENABLED]                                       INT              NOT NULL,
    [SQMGUID]                                          UNIQUEIDENTIFIER NOT NULL,
    [WORKFLOWLINEITEMNOTIFICATIONFORMAT]               INT              NOT NULL,
    [DENSITY]                                          INT              NOT NULL,
    [THEME]                                            INT              NOT NULL,
    [STARTPAGE]                                        NVARCHAR (60)    NOT NULL,
    [EMAILPROVIDERID]                                  NVARCHAR (10)    NOT NULL,
    [USERNAME]                                         NVARCHAR (81)    NOT NULL,
    [ENABLED]                                          INT              NOT NULL,
    [COMPANY]                                          NVARCHAR (4)     NOT NULL,
    [AUTOLOGOFF]                                       INT              NOT NULL,
    [NETWORKDOMAIN]                                    NVARCHAR (255)   NOT NULL,
    [ALIAS]                                            NVARCHAR (255)   NOT NULL,
    [EXTERNALUSER]                                     INT              NOT NULL,
    [USERINFO_LANGUAGE]                                NVARCHAR (7)     NOT NULL,
    [HELPLANGUAGE]                                     NVARCHAR (7)     NOT NULL,
    [PREFERREDTIMEZONE]                                INT              NOT NULL,
    [PREFERREDCALENDAR]                                INT              NOT NULL,
    [HOMEPAGEREFRESHDURATION]                          INT              NOT NULL,
    [GLOBALLISTPAGELINKMODE]                           INT              NOT NULL,
    [GLOBALEXCELEXPORTMODE]                            INT              NOT NULL,
    [USERINFO_DEFAULTPARTITION]                        INT              NOT NULL,
    [GLOBALEXCELEXPORTFILEPATH]                        NVARCHAR (259)   NOT NULL,
    [PREFERREDLOCALE]                                  NVARCHAR (86)    NOT NULL,
    [ACCOUNTTYPE]                                      INT              NOT NULL,
    [AUTOMATICURLUPDATE]                               INT              NOT NULL,
    [PARTITION]                                        NVARCHAR (20)    NOT NULL,
    [SYNCSTARTDATETIME]                                DATETIME         NOT NULL,
    CONSTRAINT [PK_SystemUserStaging] PRIMARY KEY CLUSTERED ([EXECUTIONID] ASC, [USERID] ASC, [PARTITION] ASC)
);

