CREATE TABLE [dbo].[Tax1099FieldsStaging](
	[DEFINITIONGROUP] [nvarchar](60) NOT NULL,
	[EXECUTIONID] [nvarchar](90) NOT NULL,
	[ISSELECTED] [int] NOT NULL,
	[TRANSFERSTATUS] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](50) NOT NULL,
	[MINIMUMAMOUNT] [numeric](32, 6) NOT NULL,
	[TAX1099BOX] [nvarchar](10) NOT NULL,
	[BOXNUMBER] [int] NOT NULL,
	[FORM] [nvarchar](10) NOT NULL,
	[TYPEOFTAX1099FORM] [int] NOT NULL,
	[PARTITION] [nvarchar](20) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Tax1099FieldsStaging] ADD  CONSTRAINT [PK_Tax1099FieldsStaging] PRIMARY KEY CLUSTERED 
(
	[EXECUTIONID] ASC,
	[TAX1099BOX] ASC,
	[TYPEOFTAX1099FORM] ASC,
	[DATAAREAID] ASC,
	[PARTITION] ASC
) ON [PRIMARY]
GO