CREATE TABLE [dbo].[TotalingAccountExplosion] (
    [DEFINITIONGROUP]        NVARCHAR (60) NOT NULL,
    [EXECUTIONID]            NVARCHAR (90) NOT NULL,
    [ISSELECTED]             INT           NOT NULL,
    [TRANSFERSTATUS]         INT           NOT NULL,
    [TOTALINGMAINACCOUNTID]  NVARCHAR (20) NOT NULL,
    [TOTALINGACCOUNTNAME]    NVARCHAR (60) NOT NULL,
    [CHARTOFACCOUNTS]        NVARCHAR (60) NOT NULL,
    [FROMVALUE]              NVARCHAR (30) NOT NULL,
    [TOVALUE]                NVARCHAR (30) NOT NULL,
    [INVERTTOTALSIGN]        INT           NOT NULL,
    [PARTITION]              NVARCHAR (20) NOT NULL,
    [SYNCSTARTDATETIME]      DATETIME      NOT NULL,
    [RECID]                  BIGINT        NOT NULL,
    [COMPONENTMAINACCOUNTID] NVARCHAR (20) NOT NULL,
    [COMPONENTACCOUNTNAME]   NVARCHAR (60) NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_TotalingAccountExplosion]
    ON [dbo].[TotalingAccountExplosion]([TOTALINGMAINACCOUNTID] ASC);

