CREATE TABLE [dbo].[VendorInvoiceLineStaging] (
    [DIMENSIONDISPLAYVALUE]            NVARCHAR (500)   NOT NULL,
    [MAINACCOUNTDISPLAYVALUE]          NVARCHAR (500)   NOT NULL,
    [ITEMNAME]                         NVARCHAR (120)   NOT NULL,
    [DIOTOPERATIONTYPE]                INT              NOT NULL,
    [INVENTORYSITEID]                  NVARCHAR (10)    NOT NULL,
    [INVENTORYWAREHOUSEID]             NVARCHAR (10)    NOT NULL,
    [PRODUCTSIZEID]                    NVARCHAR (10)    NOT NULL,
    [PRODUCTCOLORID]                   NVARCHAR (10)    NOT NULL,
    [PRODUCTCONFIGURATIONID]           NVARCHAR (50)    NOT NULL,
    [PRODUCTSTYLEID]                   NVARCHAR (10)    NOT NULL,
    [ITEMBATCHNUMBER]                  NVARCHAR (30)    NOT NULL,
    [ORDEREDINVENTORYSTATUSID]         NVARCHAR (10)    NOT NULL,
    [DEFINITIONGROUP]                  NVARCHAR (60)    NOT NULL,
    [EXECUTIONID]                      NVARCHAR (90)    NOT NULL,
    [ISSELECTED]                       INT              NOT NULL,
    [TRANSFERSTATUS]                   INT              NOT NULL,
    [VENDORACCOUNT]                    NVARCHAR (20)    NOT NULL,
    [CHANGEQUANTITYMANUALLY]           INT              NOT NULL,
    [CLOSEFORRECEIPT]                  INT              NOT NULL,
    [COUNTYORIGDEST]                   NVARCHAR (10)    NOT NULL,
    [CURRENCY]                         NVARCHAR (3)     NOT NULL,
    [DELIVERYNAME]                     NVARCHAR (100)   NOT NULL,
    [LINEDESCRIPTION]                  NVARCHAR (1000)  NOT NULL,
    [DIMENSIONNUMBER]                  NVARCHAR (20)    NOT NULL,
    [INVENTNOW]                        NUMERIC (32, 6)  NOT NULL,
    [INVOICEACCOUNT]                   NVARCHAR (20)    NOT NULL,
    [ITEMNUMBER]                       NVARCHAR (20)    NOT NULL,
    [NETAMOUNT]                        NUMERIC (32, 6)  NOT NULL,
    [DISCOUNT]                         NUMERIC (32, 6)  NOT NULL,
    [LINENUMBER]                       NUMERIC (32, 16) NOT NULL,
    [DISCOUNTPERCENT]                  NUMERIC (32, 6)  NOT NULL,
    [LINETYPE]                         INT              NOT NULL,
    [MULTILINEDISCOUNT]                NUMERIC (32, 6)  NOT NULL,
    [MULTILINEDISCOUNTPERCENTAGE]      NUMERIC (32, 6)  NOT NULL,
    [ADJUSTEDUNITPRICE]                NUMERIC (32, 6)  NOT NULL,
    [PDSCALCULATIONID]                 NVARCHAR (10)    NOT NULL,
    [CWUPDATE]                         NUMERIC (32, 6)  NOT NULL,
    [CWDELIVERYREMAINDER]              NUMERIC (32, 6)  NOT NULL,
    [CWREMAININGQUANTITY]              NUMERIC (32, 6)  NOT NULL,
    [PORT]                             NVARCHAR (10)    NOT NULL,
    [PRICEUNIT]                        NUMERIC (32, 12) NOT NULL,
    [RELEASEALLRETAINEDAMOUNT]         INT              NOT NULL,
    [AMOUNT]                           NUMERIC (32, 6)  NOT NULL,
    [PERCENTAGE]                       NUMERIC (32, 6)  NOT NULL,
    [RETAINAGEAMOUNT]                  NUMERIC (32, 6)  NOT NULL,
    [TOTALRETAINEDAMOUNT]              NUMERIC (32, 6)  NOT NULL,
    [RETAINPERCENTAGE]                 NUMERIC (32, 6)  NOT NULL,
    [CHARGESONPURCHASES]               NUMERIC (32, 6)  NOT NULL,
    [UNITPRICE]                        NUMERIC (32, 6)  NOT NULL,
    [UNIT]                             NVARCHAR (10)    NOT NULL,
    [RECEIVENOW]                       NUMERIC (32, 6)  NOT NULL,
    [REMAINAFTER]                      NUMERIC (32, 6)  NOT NULL,
    [REMAINAFTERINVENT]                NUMERIC (32, 6)  NOT NULL,
    [REMAINBEFORE]                     NUMERIC (32, 6)  NOT NULL,
    [REMAINBEFOREINVENT]               NUMERIC (32, 6)  NOT NULL,
    [ORIGINALDELIVERREMAINDER]         NUMERIC (32, 6)  NOT NULL,
    [VENDORINVOICELINEREVIEWSTATUS]    INT              NOT NULL,
    [STATISTICSPROCEDURE]              NVARCHAR (10)    NOT NULL,
    [PURCHASEORDER]                    NVARCHAR (20)    NOT NULL,
    [TAX1099AMOUNT]                    NUMERIC (32, 6)  NOT NULL,
    [DELIVERYSTATE]                    NVARCHAR (10)    NOT NULL,
    [TAX1099STATEAMOUNT]               NUMERIC (32, 6)  NOT NULL,
    [SALESTAXGROUP]                    NVARCHAR (10)    NOT NULL,
    [ITEMSALESTAX]                     NVARCHAR (10)    NOT NULL,
    [WITHHOLDINGTAXGROUP]              NVARCHAR (10)    NOT NULL,
    [TRANSACTIONCODE]                  NVARCHAR (10)    NOT NULL,
    [TRANSPORT]                        NVARCHAR (10)    NOT NULL,
    [COMMODITY]                        NVARCHAR (20)    NOT NULL,
    [ORIGCOUNTRYREGIONID]              NVARCHAR (10)    NOT NULL,
    [STATEOFORIGIN]                    NVARCHAR (10)    NOT NULL,
    [ACCOUNTINGDISTRIBUTIONTEMPLATEID] NVARCHAR (40)    NOT NULL,
    [PARTYID]                          NVARCHAR (40)    NOT NULL,
    [DATAAREACOMPANY]                  NVARCHAR (4)     NOT NULL,
    [PROCUREMENTCATEGORYNAME]          NVARCHAR (254)   NOT NULL,
    [PROCUREMENTCATEGORYHIERARCHYNAME] NVARCHAR (128)   NOT NULL,
    [TAX1099BOX]                       NVARCHAR (10)    NOT NULL,
    [TAX1099TYPE]                      INT              NOT NULL,
    [HEADERREFERENCE]                  NVARCHAR (20)    NOT NULL,
    [PURCHLINENUMBER]                  BIGINT           NOT NULL,
    [TAXSERVICECODE]                   NVARCHAR (10)    NOT NULL,
    [TAXWITHHOLDGROUP]                 NVARCHAR (10)    NOT NULL,
    [CFOPCODE]                         NVARCHAR (5)     NOT NULL,
    [TAXWITHHOLDITEMGROUPNAME]         NVARCHAR (60)    NOT NULL,
    [INVOICELINENUMBER]                NUMERIC (32, 16) NOT NULL,
    [BUDGETRESERVATIONLINENUMBER]      INT              NOT NULL,
    [BUDGETRESERVATIONDOCUMENTNUMBER]  NVARCHAR (20)    NOT NULL,
    [PARTITION]                        NVARCHAR (20)    NOT NULL,
    [DATAAREAID]                       NVARCHAR (4)     NOT NULL,
    [SYNCSTARTDATETIME]                DATETIME         NOT NULL,
    CONSTRAINT [PK_VendorInvoiceLineStaging] PRIMARY KEY CLUSTERED ([EXECUTIONID] ASC, [HEADERREFERENCE] ASC, [INVOICELINENUMBER] ASC, [DATAAREAID] ASC, [PARTITION] ASC)
);

