CREATE TABLE [dbo].[VendVendorBankAccountStaging] (
    [CROSSRATE]                                  NUMERIC (32, 16) NOT NULL,
    [DEFINITIONGROUP]                            NVARCHAR (60)    NOT NULL,
    [EXECUTIONID]                                NVARCHAR (90)    NOT NULL,
    [ISSELECTED]                                 INT              NOT NULL,
    [TRANSFERSTATUS]                             INT              NOT NULL,
    [VENDORBANKACCOUNTID]                        NVARCHAR (10)    NOT NULL,
    [BANKACCOUNTNUMBER]                          NVARCHAR (48)    NOT NULL,
    [BANKNAME]                                   NVARCHAR (60)    NOT NULL,
    [BANKNAMEINKANA]                             NVARCHAR (40)    NOT NULL,
    [BANKGROUPID]                                NVARCHAR (10)    NOT NULL,
    [VENDORACCOUNTNUMBER]                        NVARCHAR (20)    NOT NULL,
    [ROUTINGNUMBERTYPE]                          INT              NOT NULL,
    [ROUTINGNUMBER]                              NVARCHAR (12)    NOT NULL,
    [DUNSNUMBER]                                 NVARCHAR (9)     NOT NULL,
    [DUNS4NUMBERSUFFIX]                          NVARCHAR (4)     NOT NULL,
    [CONTROLINTERNALNUMBER]                      NVARCHAR (1)     NOT NULL,
    [SWIFTCODE]                                  NVARCHAR (20)    NOT NULL,
    [IBAN]                                       NVARCHAR (48)    NOT NULL,
    [BANKACCOUNTTYPE]                            INT              NOT NULL,
    [CORRESPONDENCEBANKACCOUNTNUMBER]            NVARCHAR (48)    NOT NULL,
    [BANKCONSTANTSYMBOL]                         NVARCHAR (10)    NOT NULL,
    [BANKSPECIFICSYMBOL]                         NVARCHAR (60)    NOT NULL,
    [ACTIVEDATE]                                 DATETIME         NOT NULL,
    [EXPIRATIONDATE]                             DATETIME         NOT NULL,
    [BANKTRANSACTIONTYPE]                        INT              NOT NULL,
    [FOREIGNBANKGROUPID]                         NVARCHAR (10)    NOT NULL,
    [FOREIGNBANKACCOUNTNUMBER]                   NVARCHAR (48)    NOT NULL,
    [FOREIGNBANKSWIFTCODE]                       NVARCHAR (20)    NOT NULL,
    [RECIPIENTTEXTCODE]                          NVARCHAR (10)    NOT NULL,
    [BANKMESSAGE]                                NVARCHAR (255)   NOT NULL,
    [RATEOFEXCHANGEREFERENCE]                    NVARCHAR (11)    NOT NULL,
    [CURRENTCURRENCYCODE]                        NVARCHAR (3)     NOT NULL,
    [ISDEFAULTBANKACCOUNTFORCURRENTCURRENCY]     INT              NOT NULL,
    [ISDEFAULTBANKACCOUNT]                       INT              NOT NULL,
    [BANKCORRESPONDENCEBANKGROUPID]              NVARCHAR (10)    NOT NULL,
    [BANKCORRESPONDENCEACCOUNTBANKGROUPID]       NVARCHAR (10)    NOT NULL,
    [INTERIMBANKCORRESPONDENCEBANKACCOUNTNUMBER] NVARCHAR (48)    NOT NULL,
    [INTERIMVENDORBANKACCOUNTNUMBER]             NVARCHAR (10)    NOT NULL,
    [CONTACTPHONENUMBER]                         NVARCHAR (20)    NOT NULL,
    [CONTACTPHONENUMBEREXTENSION]                NVARCHAR (10)    NOT NULL,
    [CONTACTMOBILEPHONENUMBER]                   NVARCHAR (20)    NOT NULL,
    [CONTACTPAGER]                               NVARCHAR (20)    NOT NULL,
    [CONTACTFAXNUMBER]                           NVARCHAR (20)    NOT NULL,
    [CONTACTEMAILADDRESS]                        NVARCHAR (80)    NOT NULL,
    [CONTACTEMAILADDRESSFORSENDINGSMS]           NVARCHAR (80)    NOT NULL,
    [CONTACTINTERNETADDRESS]                     NVARCHAR (255)   NOT NULL,
    [CONTACTTELEXNUMBER]                         NVARCHAR (20)    NOT NULL,
    [CONTACTNAME]                                NVARCHAR (60)    NOT NULL,
    [FORMATTEDADDRESS]                           NVARCHAR (250)   NOT NULL,
    [ADDRESSLOCATIONID]                          NVARCHAR (30)    NOT NULL,
    [ADDRESSDESCRIPTION]                         NVARCHAR (60)    NOT NULL,
    [ADDRESSCOUNTRY]                             NVARCHAR (10)    NOT NULL,
    [ADDRESSCOUNTRYISOCODE]                      NVARCHAR (2)     NOT NULL,
    [ADDRESSSTATE]                               NVARCHAR (10)    NOT NULL,
    [ADDRESSCITY]                                NVARCHAR (60)    NOT NULL,
    [ADDRESSCOUNTY]                              NVARCHAR (10)    NOT NULL,
    [ADDRESSSTREET]                              NVARCHAR (250)   NOT NULL,
    [ADDRESSSTREETNUMBER]                        NVARCHAR (20)    NOT NULL,
    [ADDRESSCITYINKANA]                          NVARCHAR (60)    NOT NULL,
    [ADDRESSSTREETINKANA]                        NVARCHAR (250)   NOT NULL,
    [ADDRESSLATITUDE]                            NUMERIC (32, 6)  NOT NULL,
    [ADDRESSLONGITUDE]                           NUMERIC (32, 6)  NOT NULL,
    [ADDRESSZIPCODE]                             NVARCHAR (10)    NOT NULL,
    [ADDRESSDISTRICTNAME]                        NVARCHAR (60)    NOT NULL,
    [ADDRESSPOSTBOX]                             NVARCHAR (20)    NOT NULL,
    [ADDRESSBUILDINGCOMPLIMENT]                  NVARCHAR (60)    NOT NULL,
    [ADDRESSVALIDFROM]                           DATETIME         NOT NULL,
    [ADDRESSVALIDTO]                             DATETIME         NOT NULL,
    [ADDRESSTIMEZONE]                            INT              NOT NULL,
    [PARTITION]                                  NVARCHAR (20)    NOT NULL,
    [DATAAREAID]                                 NVARCHAR (4)     NOT NULL,
    [SYNCSTARTDATETIME]                          DATETIME         NOT NULL,
    CONSTRAINT [PK_VendVendorBankAccountStaging] PRIMARY KEY CLUSTERED ([EXECUTIONID] ASC, [VENDORBANKACCOUNTID] ASC, [VENDORACCOUNTNUMBER] ASC, [DATAAREAID] ASC, [PARTITION] ASC)
);

