CREATE TABLE [dbo].[zzRLCBud] (
    [InternalID]            CHAR (10)     NOT NULL,
    [LevelName]             VARCHAR (100) NOT NULL,
    [Entity]                VARCHAR (100) NOT NULL,
    [GeographyName]         VARCHAR (100) NULL,
    [InternalPL]            VARCHAR (100) NULL,
    [ManagementLevel]       VARCHAR (100) NULL,
    [ControllableCorporate] VARCHAR (100) NULL,
    [AccountName]           VARCHAR (500) NOT NULL,
    [Project]               VARCHAR (50)  NULL,
    [Task]                  VARCHAR (50)  NULL,
    [Supplier]              VARCHAR (100) NULL,
    [CaseName]              VARCHAR (100) NULL,
    [Prioritization]        VARCHAR (100) NULL,
    [Description]           VARCHAR (500) NULL,
    [NOTES]                 VARCHAR (MAX) NULL,
    [Instructions]          VARCHAR (50)  NULL,
    [Jan2021]               FLOAT (53)    NULL,
    [Feb2021]               FLOAT (53)    NULL,
    [Mar2021]               FLOAT (53)    NULL,
    [Q12021]                FLOAT (53)    NULL,
    [Apr2021]               FLOAT (53)    NULL,
    [May2021]               FLOAT (53)    NULL,
    [Jun2021]               FLOAT (53)    NULL,
    [Q22021]                FLOAT (53)    NULL,
    [Jul2021]               FLOAT (53)    NULL,
    [Aug2021]               FLOAT (53)    NULL,
    [Sep2021]               FLOAT (53)    NULL,
    [Q32021]                FLOAT (53)    NULL,
    [Oct2021]               FLOAT (53)    NULL,
    [Nov2021]               FLOAT (53)    NULL,
    [Dec2021]               FLOAT (53)    NULL,
    [Q42021]                FLOAT (53)    NULL,
    [FY2021]                FLOAT (53)    NULL
);

