CREATE TABLE [TM].[SharepointExtract](
	ResearchProjectId int null,
	[ProjectName] [varchar](255) NULL,
	[GeneTarget] [varchar](255) NULL,
	[Franchise] [varchar](255) NULL,
	[Indication] [varchar](255) NULL,
	[CurrentStatus] [varchar](255) NULL,
	[ResearchMilestone] [varchar](255) NULL,
	[ResearchEstMilestoneDate] [varchar](255) NULL,
	[Biomarker] [varchar](255) NULL,
	[BiomarkerMilestone] [varchar](255) NULL,
	[BiomarkerEstMilestoneDate] [varchar](255) NULL,
	[TMMilestone] [varchar](255) NULL,
	[TMEstMilestoneDate] [varchar](255) NULL,
	[NextTMMilestone] [varchar](255) NULL,
	[NextTMEstMilestoneDate] [varchar](255) NULL,
	ApprovalStatus bit,
	Modified Datetime null,
	ModifiedBy [varchar](255) NULL,
	Created datetime null,
	CreatedBy  [varchar](255) NULL,
	[dbLastModifiedDate] datetime null, 
    [dbHashValue] BINARY(32) NULL,
	SyncToSP bit null
) 
