CREATE TABLE [TM].[StgBiomarkersData](
	[Biomarker] [varchar](255) NULL,
	[Species] [varchar](255) NULL,
	[Matrix] [varchar](255) NULL,
	[Lab] [varchar](255) NULL,
	[Assay/Platform] [varchar](255) NULL,
	[Requestor] [varchar](255) NULL,
	[Franchise] [varchar](255) NULL,
	[Target] [varchar](255) NULL,
	[Disease] [varchar](255) NULL,
	[Context of Use] [varchar](255) NULL,
	[Type of Endpoint] [varchar](255) NULL,
	[Bidding] [varchar](255) NULL,
	[Contract] [varchar](255) NULL,
	[Reagent Procurement] [varchar](255) NULL,
	[Method Development] [varchar](255) NULL,
	[Method Validation] [varchar](255) NULL,
	[Date requested] [varchar](255) NULL,
	[When desired] [varchar](255) NULL,
	[Franchise priority] [varchar](255) NULL,
	[Ionis Priority] [varchar](255) NULL,
	[Expected projection completion] [varchar](255) NULL,
	[State of program] [varchar](255) NULL,
	[True/False] [varchar](255) NULL,
	LoadDate datetime
)