/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 12-Feb-2021 3:13:30 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */


/* Create Tables */

CREATE TABLE [research].[CompoundNames]
(
	[CompoundName] varchar(100) NULL,
	[CompoundNameType] varchar(50) NULL,
	[CompoundNameStatus] varchar(50) NULL,
	[DateCreated] datetime NULL DEFAULT getdate(),
	[DateModified] datetime NULL,
	[CompoundNamesID] int NOT NULL IDENTITY (1, 1),
	[CompoundNumber] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [research].[CompoundNames] 
 ADD CONSTRAINT [PK_CompoundNames]
	PRIMARY KEY CLUSTERED ([CompoundNamesID] ASC)
GO

CREATE NONCLUSTERED INDEX [INDX_CompoundName_CompoundNames] 
 ON [research].[CompoundNames] ([CompoundName] ASC)
GO

CREATE NONCLUSTERED INDEX [INDX_CompoundNameType_CompoundNames] 
 ON [research].[CompoundNames] ([CompoundNameType] ASC)
GO

CREATE NONCLUSTERED INDEX [INDX_CompoundNumber_CompoundNames] 
 ON [research].[CompoundNames] ([CompoundNumber] ASC)
GO

CREATE NONCLUSTERED INDEX [INDX_CompoundNameStatus_CompoundNames] 
 ON [research].[CompoundNames] ([CompoundNameStatus] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [research].[CompoundNames] ADD CONSTRAINT [FK_CompoundNames_Compounds]
	FOREIGN KEY ([CompoundNumber]) REFERENCES [research].[Compounds] ([CompoundNumber]) ON DELETE No Action ON UPDATE No Action
GO