/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 12-Feb-2021 3:13:30 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE [research].[Compounds]
(
	[CompoundNumber] int NOT NULL,
	[ISISCreationDate] datetime NULL,
	[DateCreated] datetime NULL DEFAULT getdate()
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [research].[Compounds] 
 ADD CONSTRAINT [PK__Compound__0A328CEA5D4AB198]
	PRIMARY KEY CLUSTERED ([CompoundNumber] ASC)
GO