/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 12-Feb-2021 3:13:30 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE [research].[CompoundGenes]
(
	[EnsemblID] varchar(50) NULL,
	[Species] varchar(50) NULL,
	[SpeciesName] varchar(50) NULL,
	[TargetType] varchar(50) NULL,
	[ReleaseNum] int NULL,
	[Obsolete] bit NULL,
	[DateCreated] datetime NULL DEFAULT getdate(),
	[DateModified] datetime NULL,
	[CompoundGenesID] int NOT NULL IDENTITY (1, 1),
	[CompoundNumber] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [research].[CompoundGenes] 
 ADD CONSTRAINT [PK_CompoundGenes]
	PRIMARY KEY CLUSTERED ([CompoundGenesID] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_EnsemblID_CompoundGenes] 
 ON [research].[CompoundGenes] ([EnsemblID] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_Species_CompoundGenes] 
 ON [research].[CompoundGenes] ([Species] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_SpeciesName_CompoundGenes] 
 ON [research].[CompoundGenes] ([SpeciesName] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_TargetType_CompoundGenes] 
 ON [research].[CompoundGenes] ([TargetType] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_CompoundNumber_CompoundGenes] 
 ON [research].[CompoundGenes] ([CompoundNumber] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [research].[CompoundGenes] ADD CONSTRAINT [FK_CompoundGenes_Compounds]
	FOREIGN KEY ([CompoundNumber]) REFERENCES [research].[Compounds] ([CompoundNumber]) ON DELETE No Action ON UPDATE No Action
GO