/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 16-Feb-2021 11:12:32 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE [research].[CompoundGeneTerms]
(
	[CompoundNumber] VARCHAR(50) NULL,	-- ASO number from ISIS
	[CompoundTerm] varchar(100) NULL,	-- Either ASO number or alternative terms such as generic name, ION number, etc.
	[CompoundTermType] varchar(50) NULL,	-- Description of compound term, public, internal, ASO number, etc.
	[CompoundTermStatus] varchar(50) NULL,	-- Description of utility of term, either in current use or obsolete
	[EnsemblID] varchar(100) NULL,	-- EnsemblID associated with the compound at time of design derived from ISIS.
	[Species] varchar(50) NULL,	-- Common name of species associated with ensembl ID
	[TargetType] varchar(50) NULL,	-- Either 'inferred' or 'intended'. 'Intended' means that the ASO sequence is explicitly designed to target the gene, 'inferred' means there's sufficient sequence similarity that off-target binding is likely.
	[TargetObsolete] bit NULL,	-- A target is considered obsolete if subsequent ensembl releases determine that the ASO sequence does not actually target the intended gene.
	[GeneTerm] varchar(1000) NULL,	-- A gene symbol or name derived from ensembl based on the ensembl id.
	[GeneTermType] varchar(50) NULL,	-- Description of the GeneTerm, either a GeneSymbol or GeneName.
	[GeneTermStatus] varchar(50) NULL,	-- Term status is 'primary' for GeneSymbols if it is the canonical name in the ensembl database, all other symbols are extracted from the ensembl synonyms list for that gene. All GeneNames are primary names, there are no synonyms
	[CompoundGeneTermsID] int NOT NULL IDENTITY (1, 1)
)ON [PRIMARY]
GO

ALTER TABLE [research].[CompoundGeneTerms]  
 ADD CONSTRAINT [PK_CompoundGeneTerms]
	PRIMARY KEY CLUSTERED ([CompoundGeneTermsID] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_CompoundTerm_CompoundGeneTerms] 
 ON [research].[CompoundGeneTerms] ([CompoundTerm] ASC);
 GO

CREATE NONCLUSTERED INDEX [idx_CompoundNumber_CompoundGeneTerms] 
 ON [research].[CompoundGeneTerms] ([CompoundNumber] ASC);
 GO

CREATE NONCLUSTERED INDEX [idx_EnsemblID_CompoundGeneTerms] 
 ON [research].[CompoundGeneTerms] ([EnsemblID] ASC);
 GO

CREATE NONCLUSTERED INDEX [idx_GeneTerm_CompoundGeneTerms] 
 ON [research].[CompoundGeneTerms] ([GeneTerm] ASC);
 GO
CREATE NONCLUSTERED INDEX [idx_GeneTermType_CompoundGeneTerms]
 ON [research].[CompoundGeneTerms]([GeneTermType] ASC);
 GO
CREATE NONCLUSTERED INDEX [idx_Species_CompoundGeneTerms]
 ON [research].[CompoundGeneTerms]([Species] ASC);
 GO
CREATE NONCLUSTERED INDEX [idx_GeneTermStatus_CompoundGeneTerms]
 ON [research].[CompoundGeneTerms]([GeneTermStatus] ASC);
 GO