/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 12-Feb-2021 3:13:30 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */


/* Create Tables */

CREATE TABLE [research].[GeneSymbols]
(
	[EnsemblID] varchar(50) NULL,
	[GeneSymbol] varchar(500) NULL,
	[Species] varchar(50) NULL,
	[GeneSymbolStatus] varchar(50) NULL,
	[DateCreated] datetime NULL DEFAULT getdate(),
	[DateModified] datetime NULL,
	[GeneSymbolsID] int NOT NULL IDENTITY (1, 1)
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [research].[GeneSymbols] 
 ADD CONSTRAINT [PK_GeneSymbols]
	PRIMARY KEY CLUSTERED ([GeneSymbolsID] ASC)
GO

ALTER TABLE [research].[GeneSymbols] 
 ADD CONSTRAINT [unique_EnsemblIDSymbol] UNIQUE NONCLUSTERED ([EnsemblID] ASC,[GeneSymbol] ASC)
GO

CREATE NONCLUSTERED INDEX [INDX_EnsemblID_GeneSymbols] 
 ON [research].[GeneSymbols] ([EnsemblID] ASC)
GO

CREATE NONCLUSTERED INDEX [INDX_GeneSymbol_GeneSymbols] 
 ON [research].[GeneSymbols] ([GeneSymbol] ASC)
GO

CREATE NONCLUSTERED INDEX [INDX_Species_GeneSymbols] 
 ON [research].[GeneSymbols] ([Species] ASC)
GO

CREATE NONCLUSTERED INDEX [INDX_GeneSymbolStatus_GeneSymbols] 
 ON [research].[GeneSymbols] ([GeneSymbolStatus] ASC)
GO