/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 16-Feb-2021 12:45:03 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE [research].[GeneTerms]
(
	[EnsemblID] varchar(50) NULL,	-- EnsemblID associated with the compound at time of design derived from ISIS.
	[Species] varchar(50) NULL,	-- Common name of species associated with ensembl ID
	[GeneTerm] varchar(1000) NULL,	-- A gene symbol or name derived from ensembl based on the ensembl id.
	[GeneTermType] varchar(50) NULL,	-- Description of the GeneTerm, either a GeneSymbol or GeneName.
	[GeneTermStatus] varchar(50) NULL,	-- Term status is 'primary' for GeneSymbols if it is the canonical name in the ensembl database, all other symbols are extracted from the ensembl synonyms list for that gene. All GeneNames are primary names, there are no synonyms
	[GeneTermsID] int NOT NULL IDENTITY (1, 1),
	[PrimarySymbol] varchar(1000) NULL,
	[PrimaryName] varchar(1000) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [research].[GeneTerms] 
 ADD CONSTRAINT [PK_GeneTerms]
	PRIMARY KEY CLUSTERED ([GeneTermsID] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_EnsemblID_GeneTerms] 
 ON [research].[GeneTerms] ([EnsemblID] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_GeneTerm_GeneTerms] 
 ON [research].[GeneTerms] ([GeneTerm] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_GeneTermType_GeneTerms] 
 ON [research].[GeneTerms] ([GeneTermType] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_Species_GeneTerms] 
 ON [research].[GeneTerms] ([Species] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_GeneTermStatus_GeneTerms] 
 ON [research].[GeneTerms] ([GeneTermStatus] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_PrimarySymbol_GeneTerms] 
 ON [research].[GeneTerms] ([PrimarySymbol] ASC)
GO

CREATE NONCLUSTERED INDEX [idx_PrimaryName] 
 ON [research].[GeneTerms] ([PrimaryName] ASC)
GO

