/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 11-Feb-2021 10:26:11 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[legal].[ContractResponsibilities]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [legal].[ContractResponsibilities]
GO

/* Create Tables */

CREATE TABLE [legal].[ContractResponsibilities]
(
	[ContractResponsibility] varchar(50) NULL,
	[ContractResponsibilitiesID] int NOT NULL IDENTITY (1, 1)
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [legal].[ContractResponsibilities] 
 ADD CONSTRAINT [PK_Contractresponsibilities]
	PRIMARY KEY CLUSTERED ([ContractResponsibilitiesID] ASC)
GO