/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 18-Jan-2021 12:01:18 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */


/* Create Tables */

CREATE TABLE [legal].[ContractContractTypes]
(
	[ContractContractTypesID] int NOT NULL IDENTITY (1, 1),
	[LegalContractsID] int NULL,
	[ContractTypesID] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [legal].[ContractContractTypes] 
 ADD CONSTRAINT [PK_ContractContractTypes]
	PRIMARY KEY CLUSTERED ([ContractContractTypesID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [legal].[ContractContractTypes] ADD CONSTRAINT [FK_ContractContractTypes_ContractTypes]
	FOREIGN KEY ([ContractTypesID]) REFERENCES [legal].[ContractTypes] ([ContractTypesID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [legal].[ContractContractTypes] ADD CONSTRAINT [FK_ContractContractTypes_LegalContracts]
	FOREIGN KEY ([LegalContractsID]) REFERENCES [legal].[LegalContracts] ([LegalContractsID]) ON DELETE No Action ON UPDATE No Action
GO