/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 18-Jan-2021 12:01:18 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE [legal].[ContractTypes]
(
	[ContractType] varchar(200) NULL,
	[ContractTypesID] int NOT NULL IDENTITY (1, 1)
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [legal].[ContractTypes] 
 ADD CONSTRAINT [PK_ContractTypes]
	PRIMARY KEY CLUSTERED ([ContractTypesID] ASC)
GO