/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 18-Jan-2021 12:01:18 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */


/* Create Tables */

CREATE TABLE [legal].[LegalOrganization]
(
	[CongaCompanyID] varchar(100) NULL,
	[OrganizationName] varchar(200) NULL,
	[OrganizationNumber] varchar(100) NULL,
	[CompanyGroup] varchar(200) NULL,
	[DunsNumber] varchar(100) NULL,
	[OrganizationType] varchar(100) NULL,
	[OrganizationCategory] varchar(100) NULL,
	[OrganizationStatus] varchar(100) NULL,
	[LegalOrganizationID] int NOT NULL IDENTITY (1, 1)
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [legal].[LegalOrganization] 
 ADD CONSTRAINT [PK_LegalOrganization]
	PRIMARY KEY CLUSTERED ([LegalOrganizationID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [legal].[LegalOrganization] ADD CONSTRAINT [FK_LegalContracts_LegalOrganization]
	FOREIGN KEY ([LegalOrganizationID]) REFERENCES [legal].[LegalOrganization] ([LegalOrganizationID]) ON DELETE No Action ON UPDATE No Action
GO