/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 20-Jan-2021 12:01:10 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE [legal].[LegalContracts]
(
	[CongaContractID] varchar(50) NULL,
	[ContractNumber] varchar(50) NULL,
	[AgreementType] varchar(200) NULL,
	[Purpose] varchar(200) NULL,
	[LegalEntity] varchar(50) NULL,
	[OriginalExpirationDate] datetime NULL,
	[EffectiveDate] datetime NULL,
	[CurrentExpirationDate] datetime NULL,
	[TermType] varchar(200) NULL,
	[Status] varchar(200) NULL,
	[Description] varchar(5000) NULL,
	[ContractGroup] varchar(200) NULL,
	[NoticePeriod] varchar(5000) NULL,
	[StudyNumber] varchar(50) NULL,
	[NoticeDate] datetime NULL,
	[LastUpdateDate] datetime NULL,
	[LegalContractsID] int NOT NULL IDENTITY (1, 1),
	[LegalOrganizationID] int NULL,
	[ParentContractID] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [legal].[LegalContracts] 
 ADD CONSTRAINT [PK_LegalContracts]
	PRIMARY KEY CLUSTERED ([LegalContractsID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [legal].[LegalContracts] ADD CONSTRAINT [FK_ParentContractID]
	FOREIGN KEY ([ParentContractID]) REFERENCES [legal].[LegalContracts] ([LegalContractsID]) ON DELETE No Action ON UPDATE No Action
GO
