/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 11-Feb-2021 10:26:11 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[legal].[FK_Personcontractresponsibilities_Congaperson]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [legal].[PersonContractResponsibilities] DROP CONSTRAINT [FK_Personcontractresponsibilities_Congaperson]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[legal].[FK_Personcontractresponsibilities_Contractresponsibilities]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [legal].[PersonContractResponsibilities] DROP CONSTRAINT [FK_Personcontractresponsibilities_Contractresponsibilities]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[legal].[PersonContractResponsibilities]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [legal].[PersonContractResponsibilities]
GO

/* Create Tables */

CREATE TABLE [legal].[PersonContractResponsibilities]
(
	[CongaPersonID] int NULL,
	[PersonContractResponsibilitiesID] int NOT NULL IDENTITY (1, 1),
	[LegalContractsID] int NULL,
	[ContractResponsibilitiesID] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [legal].[PersonContractResponsibilities] 
 ADD CONSTRAINT [PK_Personcontractresponsibilities]
	PRIMARY KEY CLUSTERED ([PersonContractResponsibilitiesID] ASC)
GO

CREATE NONCLUSTERED INDEX [INDX_LegalContractsID] 
 ON [legal].[PersonContractResponsibilities] ([LegalContractsID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [legal].[PersonContractResponsibilities] ADD CONSTRAINT [FK_Personcontractresponsibilities_Congaperson]
	FOREIGN KEY ([CongaPersonID]) REFERENCES  () ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [legal].[PersonContractResponsibilities] ADD CONSTRAINT [FK_Personcontractresponsibilities_Contractresponsibilities]
	FOREIGN KEY ([ContractResponsibilitiesID]) REFERENCES [legal].[ContractResponsibilities] ([ContractResponsibilitiesID]) ON DELETE No Action ON UPDATE No Action
GO