CREATE VIEW [shared_mart].[DimAddress]
AS
SELECT [ID]
      ,[AddresseeName]
      ,[StreetAddress1]
      ,[StreetAddress2]
      ,[City]
      ,[StateProvince]
      ,[Country]
      ,[PostalCode]
      ,[AddresseeNameOrigencoding]
      ,[Street_Address1Origencoding]
      ,[Street_Address2Origencoding]
      ,[CityOrigencoding]
      ,[StateProvinceOrigencoding]
      ,[CountryOrigencoding]
      ,[PostalCodeOrigencoding]
      ,[StartDate]
      ,[EndDate]
      ,[AddressID]
      ,a.[LocationInfoID]
      ,li.[OrganizationID]
      ,li.[LocationType]
FROM shared.LocationInfo li, shared.Address a
WHERE a.LocationInfoID = li.LocationInfoID