
CREATE FUNCTION [dbo].[IONIS_UltiCompanyToD365](@UltiCompany char(5))
RETURNS char(4)
AS
BEGIN
	DECLARE @returnValue char(4);
	SET @returnValue = CASE @UltiCompany
				WHEN 'AKCAT' THEN 'AKUS'
				WHEN 'AKCCA' THEN 'AKCA'
				WHEN 'AKCCH' THEN 'AKUS'
				WHEN 'AKCDE' THEN 'AKDE'
				WHEN 'AKCDR' THEN 'AKUS'
				WHEN 'AKCEA' THEN 'AKUS'
				WHEN 'AKCFR' THEN 'AKFR'
				WHEN 'AKCIE' THEN 'AKIE'
				WHEN 'AKCIT' THEN 'AKIT'
				WHEN 'AKCPT' THEN 'AKPT'
				WHEN 'AKCSE' THEN 'AKUS'
				WHEN 'AKCSP' THEN 'AKSP'
				WHEN 'AKCUK' THEN 'AKUK'
				WHEN 'IBIS' THEN 'IONS'
				WHEN 'ISIS' THEN 'IONS'
				WHEN 'REGS' THEN 'REGS'
				WHEN 'SING' THEN 'SING'
				WHEN 'TEMP' THEN 'TEMP'
			ELSE 'UNK' END

	RETURN @returnValue;
END
