CREATE VIEW [legal_mart].[DimLegalContracts]
AS
SELECT [CongaContractID]
      ,[ContractNumber]
      ,[AgreementType]
      ,[Purpose]
      ,[LegalEntity]
      ,[OriginalExpirationDate]
      ,[EffectiveDate]
      ,[CurrentExpirationDate]
      ,[TermType]
      ,[Status]
      ,[Description]
      ,[LastUpdateDate]
      ,[LegalContractsID]
      ,[LegalOrganizationID]
      ,[ParentContractID]
      ,[ContractGroup]
      ,[NoticePeriod]
      ,[StudyNumber]
      ,[NoticeDate]
  FROM [legal].[LegalContracts]