/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 22-Jun-2021 11:24:53 AM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE [clinical].[ClinicalStudySites]
(
	[StartDate] datetime NULL,
	[EndDate] datetime NULL,
	[Status] varchar(2000) NULL,
	[ClinicalStudySitesID] int NOT NULL IDENTITY (1, 1),
	[ClinicalSiteID] int NOT NULL,
	[ClinicalStudyID] int NOT NULL,
	[SiteInitiationDate] datetime NULL,
	[CTMS_PrimaryInvestigator] varchar(150) NULL,	-- Name of the PI from the original source file.  May differ from the name in the MDM system.
	[MaximumNumberOfSubjects] int NULL,	-- Maximum number of subjects for this site from the trial recruitment projections.
	[CTMS_Status] varchar(100) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [clinical].[ClinicalStudySites] 
 ADD CONSTRAINT [PK_ClinicalStudySites]
	PRIMARY KEY CLUSTERED ([ClinicalStudySitesID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [clinical].[ClinicalStudySites] ADD CONSTRAINT [FK_ClinicalStudySites_ClinicalSite]
	FOREIGN KEY ([ClinicalSiteID]) REFERENCES [clinical].[ClinicalSite] ([ClinicalSiteID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [clinical].[ClinicalStudySites] ADD CONSTRAINT [FK_ClinicalStudySites_ClinicalStudy]
	FOREIGN KEY ([ClinicalStudyID]) REFERENCES [clinical].[ClinicalStudy] ([ClinicalStudyID]) ON DELETE No Action ON UPDATE No Action
GO
